# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TMMS_Graphs.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphsWindow(object):
    def setupUi(self, GraphsWindow):
        GraphsWindow.setObjectName("GraphsWindow")
        GraphsWindow.resize(1280, 910)
        GraphsWindow.setMouseTracking(False)
        GraphsWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(GraphsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 0, 1231, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.A_axes_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.A_axes_layout.setContentsMargins(0, 0, 0, 0)
        self.A_axes_layout.setObjectName("A_axes_layout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 450, 1231, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.B_axes_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.B_axes_layout.setContentsMargins(0, 0, 0, 0)
        self.B_axes_layout.setObjectName("B_axes_layout")
        self.A_PB_1 = QtWidgets.QPushButton(self.centralwidget)
        self.A_PB_1.setGeometry(QtCore.QRect(454, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.A_PB_1.setFont(font)
        self.A_PB_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.A_PB_1.setObjectName("A_PB_1")
        self.A_PB_2 = QtWidgets.QPushButton(self.centralwidget)
        self.A_PB_2.setGeometry(QtCore.QRect(570, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.A_PB_2.setFont(font)
        self.A_PB_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.A_PB_2.setObjectName("A_PB_2")
        self.A_PB_3 = QtWidgets.QPushButton(self.centralwidget)
        self.A_PB_3.setGeometry(QtCore.QRect(690, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.A_PB_3.setFont(font)
        self.A_PB_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.A_PB_3.setObjectName("A_PB_3")
        self.B_PB_2 = QtWidgets.QPushButton(self.centralwidget)
        self.B_PB_2.setGeometry(QtCore.QRect(570, 450, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.B_PB_2.setFont(font)
        self.B_PB_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.B_PB_2.setObjectName("B_PB_2")
        self.B_PB_1 = QtWidgets.QPushButton(self.centralwidget)
        self.B_PB_1.setGeometry(QtCore.QRect(450, 450, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.B_PB_1.setFont(font)
        self.B_PB_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.B_PB_1.setObjectName("B_PB_1")
        self.B_PB_3 = QtWidgets.QPushButton(self.centralwidget)
        self.B_PB_3.setGeometry(QtCore.QRect(690, 450, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.B_PB_3.setFont(font)
        self.B_PB_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.B_PB_3.setObjectName("B_PB_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 430, 1281, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.A_txt = QtWidgets.QLabel(self.centralwidget)
        self.A_txt.setGeometry(QtCore.QRect(990, 0, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.A_txt.setFont(font)
        self.A_txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.A_txt.setObjectName("A_txt")
        self.B_txt = QtWidgets.QLabel(self.centralwidget)
        self.B_txt.setGeometry(QtCore.QRect(990, 450, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.B_txt.setFont(font)
        self.B_txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.B_txt.setObjectName("B_txt")
        GraphsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GraphsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        GraphsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GraphsWindow)
        self.statusbar.setObjectName("statusbar")
        GraphsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GraphsWindow)
        QtCore.QMetaObject.connectSlotsByName(GraphsWindow)

    def retranslateUi(self, GraphsWindow):
        _translate = QtCore.QCoreApplication.translate
        GraphsWindow.setWindowTitle(_translate("GraphsWindow", "TMMS Time Serie Graphs"))
        self.A_PB_1.setText(_translate("GraphsWindow", "T-001"))
        self.A_PB_2.setText(_translate("GraphsWindow", "Horizontal"))
        self.A_PB_3.setText(_translate("GraphsWindow", "Primary"))
        self.B_PB_2.setText(_translate("GraphsWindow", "Vertical"))
        self.B_PB_1.setText(_translate("GraphsWindow", "T-001"))
        self.B_PB_3.setText(_translate("GraphsWindow", "Primary"))
        self.A_txt.setText(_translate("GraphsWindow", "Date:\n"
"Movement:"))
        self.B_txt.setText(_translate("GraphsWindow", "Date:\n"
"Movement:"))
